services:
  fiber:
    build:
      context: .
      dockerfile: Dockerfile
    image: go-fitbyte-prod 
    ports:
      - "7880:7880"
    restart: unless-stopped
    networks:
      - appnet

networks:
  appnet:
